# Generated by Django 4.1.1 on 2022-09-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_rename_books_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('a', 'Available'), ('n', 'No available')], default='a', max_length=200),
        ),
    ]
