# Generated by Django 4.1.1 on 2022-09-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('a', 'Available'), ('n', 'No available')], default=False, max_length=200),
        ),
    ]
