# Generated by Django 4.1.1 on 2022-09-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_alter_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='checked',
            field=models.CharField(choices=[('no', 'None')], default=False, max_length=200),
        ),
    ]
