# Generated by Django 4.1.1 on 2022-09-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0008_alter_book_checked_alter_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='checked',
            field=models.CharField(blank=True, choices=[('None', 'None')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('No available', 'No available')], max_length=200, null=True),
        ),
    ]
